name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - cmd: "clippy"
            title: "Check the codebase using Clippy"
          - cmd: "fmt --check --message-format short"
            title: "Check if the file is formatted correctly or not"
          - cmd: "test"
            title: "Check if the test passes"

      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "check-${{ matrix.cmd }}"

      - name: Install toolchains
        run: rustup update

      - name: ${{ matrix.title }}
        run: cargo ${{ matrix.cmd }}
